#!/bin/bash

exe_file="lab2"
main_dir=$(pwd)
tmp_dir="${main_dir}/template_data"

mkdir ${tmp_dir}
cd ${tmp_dir}

cmake ${main_dir}
make

mv ${exe_file} ${main_dir}

cd ${main_dir}

while [ -n "$1" ]
do
    case "$1" in
        -clean) rm -fr ${tmp_dir} ;;
        -pedantic) 
            rm -rf ${tmp_dir}
            clear
            ./${exe_file}
            rm -rf ${exe_file}
        ;;
        *) ;;
    esac
    shift
done